import React from 'react';
import { useTranslation } from 'react-i18next';
import { 
  Container, 
  Typography, 
  Box, 
  Paper, 
  Grid,
  Card,
  CardContent,
  CardMedia,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Divider
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import './EmfInfo.css';

const EmfInfo = () => {
  const { t } = useTranslation();
  
  const faqItems = [
    {
      question: 'What is electromagnetic radiation?',
      answer: 'Electromagnetic radiation consists of waves of electric and magnetic energy moving together through space. These waves are generated by the movement of electrical charges and can travel through empty space as well as through air and other materials.'
    },
    {
      question: 'What are the different types of EMF?',
      answer: 'EMF can be categorized into non-ionizing (low to mid-frequency) radiation, which includes radio waves, microwaves, infrared, and visible light, and ionizing (high-frequency) radiation, which includes ultraviolet, X-rays, and gamma rays.'
    },
    {
      question: 'Are cell phones and Wi-Fi routers safe?',
      answer: 'Cell phones and Wi-Fi routers emit non-ionizing radiation. Current scientific evidence does not conclusively link exposure to RF energy from mobile devices with any known health problems at or below the RF exposure limits set by regulatory authorities.'
    },
    {
      question: 'What are the safety standards for EMF exposure?',
      answer: 'Various organizations like ICNIRP (International Commission on Non-Ionizing Radiation Protection) and IEEE (Institute of Electrical and Electronics Engineers) have established safety guidelines. These guidelines set limits for EMF exposure that are designed to protect against all established health effects.'
    },
    {
      question: 'How is EMF measured?',
      answer: 'EMF is typically measured using specialized instruments like spectrum analyzers, EMF meters, and field strength meters. The units of measurement depend on the type of field being measured: electric fields are measured in volts per meter (V/m), magnetic fields in tesla (T) or gauss (G), and power density in watts per square meter (W/m²).'
    }
  ];
  
  return (
    <Container maxWidth="xl" className="emf-info-page">
      <Box sx={{ my: 4 }}>
        <Typography variant="h3" component="h1" gutterBottom>
          {t('emfInfo.title')}
        </Typography>
        <Typography variant="h6" color="text.secondary" paragraph>
          {t('emfInfo.description')}
        </Typography>
      </Box>
      
      <Grid container spacing={4}>
        <Grid item xs={12} md={6}>
          <Paper elevation={3} sx={{ p: 3 }}>
            <Typography variant="h4" gutterBottom>
              {t('emfInfo.whatIsEmf')}
            </Typography>
            
            <Typography variant="body1" paragraph>
              Electromagnetic fields (EMF) are a combination of invisible electric and magnetic fields of force. They are generated by natural phenomena like the Earth's magnetic field but also by human activities, mainly through the use of electricity.
            </Typography>
            
            <Typography variant="body1" paragraph>
              EMF is all around us. It comes from both natural sources (such as the sun) and man-made sources (such as wireless communications, power lines, electrical appliances, and broadcasting).
            </Typography>
            
            <Typography variant="h5" gutterBottom sx={{ mt: 3 }}>
              {t('emfInfo.emfSpectrum')}
            </Typography>
            
            <Typography variant="body1" paragraph>
              The electromagnetic spectrum encompasses all forms of electromagnetic radiation and is typically divided into seven regions in order of decreasing wavelength and increasing energy and frequency:
            </Typography>
            
            <ul>
              <li>Radio waves</li>
              <li>Microwaves</li>
              <li>Infrared radiation</li>
              <li>Visible light</li>
              <li>Ultraviolet radiation</li>
              <li>X-rays</li>
              <li>Gamma rays</li>
            </ul>
            
            <Typography variant="body1" paragraph>
              The EMF monitoring system primarily focuses on radio frequency (RF) radiation from sources like mobile networks, broadcasting, and other wireless communications.
            </Typography>
          </Paper>
        </Grid>
        
        <Grid item xs={12} md={6}>
          <Card sx={{ mb: 4 }}>
            <CardMedia
              component="img"
              height="300"
              image="https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80"
              alt="Electromagnetic spectrum visualization"
            />
            <CardContent>
              <Typography variant="subtitle1" align="center">
                Visualization of the electromagnetic spectrum
              </Typography>
            </CardContent>
          </Card>
          
          <Paper elevation={3} sx={{ p: 3 }}>
            <Typography variant="h4" gutterBottom>
              {t('emfInfo.healthEffects')}
            </Typography>
            
            <Typography variant="body1" paragraph>
              The potential health effects of EMF exposure have been the subject of scientific research and public debate. According to the World Health Organization (WHO) and other international bodies, current evidence does not confirm the existence of any health consequences from exposure to low-level electromagnetic fields.
            </Typography>
            
            <Typography variant="body1" paragraph>
              However, some gaps in knowledge about biological effects exist and need further research. This is why continuous monitoring and adherence to established safety guidelines are important.
            </Typography>
          </Paper>
        </Grid>
      </Grid>
      
      <Box sx={{ my: 4 }}>
        <Typography variant="h4" gutterBottom>
          {t('emfInfo.faq')}
        </Typography>
        
        {faqItems.map((item, index) => (
          <Accordion key={index}>
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls={`panel${index}-content`}
              id={`panel${index}-header`}
            >
              <Typography variant="h6">{item.question}</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="body1">{item.answer}</Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Box>
      
      <Paper elevation={3} sx={{ p: 3, my: 4 }}>
        <Typography variant="h4" gutterBottom>
          {t('emfInfo.safetyStandards')}
        </Typography>
        
        <Typography variant="body1" paragraph>
          Various international and national organizations have established safety guidelines for EMF exposure. These include:
        </Typography>
        
        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  ICNIRP Guidelines
                </Typography>
                <Typography variant="body2">
                  The International Commission on Non-Ionizing Radiation Protection (ICNIRP) provides scientific advice and guidance on the health and environmental effects of non-ionizing radiation.
                </Typography>
                <Divider sx={{ my: 2 }} />
                <Typography variant="body2">
                  <strong>Reference levels for general public exposure:</strong>
                </Typography>
                <Typography variant="body2">
                  - 100 kHz to 10 MHz: 83 V/m
                </Typography>
                <Typography variant="body2">
                  - 10 MHz to 400 MHz: 28 V/m
                </Typography>
                <Typography variant="body2">
                  - 400 MHz to 2 GHz: 1.375 × f^0.5 V/m (where f is in MHz)
                </Typography>
                <Typography variant="body2">
                  - 2 GHz to 300 GHz: 61 V/m
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          
          <Grid item xs={12} md={6}>
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  IEEE Standards
                </Typography>
                <Typography variant="body2">
                  The Institute of Electrical and Electronics Engineers (IEEE) develops standards for EMF exposure through its International Committee on Electromagnetic Safety (ICES).
                </Typography>
                <Divider sx={{ my: 2 }} />
                <Typography variant="body2">
                  <strong>Maximum Permissible Exposure (MPE) for general public:</strong>
                </Typography>
                <Typography variant="body2">
                  Similar to ICNIRP guidelines but with some variations in specific frequency ranges.
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </Paper>
    </Container>
  );
};

export default EmfInfo;